# Generated by Django 3.2.25 on 2026-09-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_filter', '0003_playlistchannel_first_seen'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlistchannel',
            constraint=models.UniqueConstraint(fields=('tvg_name',), name='unique name for PlaylistChannel'),
        ),
    ]
